// Generates the PWA raster icons from the single source of truth, src/app/icon.svg.
// Re-run after editing the SVG:  node scripts/build-icons.mjs
//
// - icon-192.png / icon-512.png  → manifest "any" icons (the SVG as-authored, rounded corners)
// - icon-maskable-512.png        → manifest "maskable" icon: full-bleed background with the mark
//   pulled into the safe zone, so Android's mask can't clip it.
import sharp from "sharp";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const svg = readFileSync(join(root, "src/app/icon.svg"));
const outDir = join(root, "public/icons");
mkdirSync(outDir, { recursive: true });

// High render density so the vector rasterizes crisply before any downscale.
const render = (size) => sharp(svg, { density: 512 }).resize(size, size);

for (const size of [192, 512]) {
  await render(size).png().toFile(join(outDir, `icon-${size}.png`));
}

// Maskable: composite the mark (scaled into the central safe zone) onto a full-bleed
// background matching the SVG's own panel color, so there are no transparent corners.
const CANVAS = 512;
const MARGIN = Math.round(CANVAS * 0.14); // ~72px → mark sits within the ~72% safe zone
const mark = await render(CANVAS - MARGIN * 2).png().toBuffer();
await sharp({ create: { width: CANVAS, height: CANVAS, channels: 4, background: "#0f151a" } })
  .composite([{ input: mark, top: MARGIN, left: MARGIN }])
  .png()
  .toFile(join(outDir, "icon-maskable-512.png"));

console.log("wrote public/icons/{icon-192,icon-512,icon-maskable-512}.png");

// ── Apple touch startup images (iOS PWA splash) ──────────────────────────────
// iOS ignores the web manifest for the launch screen: a standalone install shows a blank screen on
// cold start unless it finds an <link rel="apple-touch-startup-image"> whose media query matches the
// device exactly. We render the mark centered on the app background for every current iPhone/iPad,
// both orientations, and emit the matching <link> data as src/app/apple-splash.ts (imported by the
// root layout's `appleWebApp.startupImage` metadata). Regenerate after editing the icon or matrix.
const BG = "#0a0d0f"; // --color-bg, so the splash is seamless with the app's dark shell
const splashDir = join(root, "public/splash");
mkdirSync(splashDir, { recursive: true });

// Unique (logical width, logical height in portrait, device-pixel-ratio) triples covering current
// iPhones and iPads. Many models share one triple (e.g. X / XS / 11 Pro / 12–13 mini → 375×812@3);
// one entry per triple is all iOS needs to match.
const DEVICES = [
  { lw: 375, lh: 667, r: 2 }, // iPhone SE / 8 / 7 / 6s
  { lw: 414, lh: 736, r: 3 }, // iPhone 8 Plus
  { lw: 375, lh: 812, r: 3 }, // iPhone X / XS / 11 Pro / 12–13 mini
  { lw: 414, lh: 896, r: 2 }, // iPhone XR / 11
  { lw: 414, lh: 896, r: 3 }, // iPhone XS Max / 11 Pro Max
  { lw: 390, lh: 844, r: 3 }, // iPhone 12 / 12 Pro / 13 / 13 Pro / 14
  { lw: 428, lh: 926, r: 3 }, // iPhone 12–13 Pro Max / 14 Plus
  { lw: 393, lh: 852, r: 3 }, // iPhone 14 Pro / 15 / 15 Pro / 16
  { lw: 430, lh: 932, r: 3 }, // iPhone 14 Pro Max / 15 Plus / 15 Pro Max / 16 Plus
  { lw: 402, lh: 874, r: 3 }, // iPhone 16 Pro
  { lw: 440, lh: 956, r: 3 }, // iPhone 16 Pro Max
  { lw: 744, lh: 1133, r: 2 }, // iPad mini (6th/7th gen)
  { lw: 768, lh: 1024, r: 2 }, // iPad mini (older) / iPad 9.7 / Air
  { lw: 810, lh: 1080, r: 2 }, // iPad 10.2
  { lw: 820, lh: 1180, r: 2 }, // iPad Air 10.9 / 11
  { lw: 834, lh: 1112, r: 2 }, // iPad Pro 10.5
  { lw: 834, lh: 1194, r: 2 }, // iPad Pro 11
  { lw: 1024, lh: 1366, r: 2 }, // iPad Pro 12.9
];

// The mark, centered on a solid BG canvas of exactly (pw × ph) physical pixels.
async function splash(pw, ph) {
  const iconPx = Math.round(Math.min(pw, ph) * 0.26);
  const icon = await sharp(svg, { density: 512 }).resize(iconPx, iconPx).png().toBuffer();
  await sharp({ create: { width: pw, height: ph, channels: 4, background: BG } })
    .composite([{ input: icon, gravity: "center" }])
    .png()
    .toFile(join(splashDir, `apple-splash-${pw}x${ph}.png`));
}

const splashEntries = [];
for (const { lw, lh, r } of DEVICES) {
  const pw = lw * r;
  const ph = lh * r;
  await splash(pw, ph); // portrait
  await splash(ph, pw); // landscape
  // device-width/height stay at the portrait logical dims for both orientations; only the
  // orientation clause differs (the widely-used iOS startup-image convention).
  const base = `(device-width: ${lw}px) and (device-height: ${lh}px) and (-webkit-device-pixel-ratio: ${r})`;
  splashEntries.push({ url: `/splash/apple-splash-${pw}x${ph}.png`, media: `${base} and (orientation: portrait)` });
  splashEntries.push({ url: `/splash/apple-splash-${ph}x${pw}.png`, media: `${base} and (orientation: landscape)` });
}

const splashTs =
  `// GENERATED by scripts/build-icons.mjs — do not edit by hand; re-run the script to update.\n` +
  `// iOS PWA launch images: one apple-touch-startup-image <link> per device/orientation, consumed\n` +
  `// by the root layout's \`appleWebApp.startupImage\` metadata (src/app/layout.tsx).\n` +
  `export const appleSplashScreens = ${JSON.stringify(splashEntries, null, 2)};\n`;
writeFileSync(join(root, "src/app/apple-splash.ts"), splashTs);

console.log(`wrote ${splashEntries.length} splash images to public/splash + src/app/apple-splash.ts`);
